name: Deploy AI Image Analyzer
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust if using Node.js, etc.
      - name: Deploy to Hugging Face Spaces
        uses: huggingface/huggingface_hub@main
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_id: MudauRI/AI-image-analyzer
          space_sdk: gradio  # or "streamlit" if applicable
